### PR TITLE
Shorten 3PAR object names

### PR DESCRIPTION
**Pull request by soudnyl**
Hi, I've made a patch to shorten 3PAR object names. It is a small, but breaking change. 

The reason for it is, that 3PAR has very limited name lengths (31 characters for VVs, 27 for VVsets) and the names as they are now easily cause trouble with some 3PAR functionality. 
For example 3PAR Remote Copy Groups are limited to only 22 characters and when you have a VV like 'dev.one.vm.10700.0.vv', that's already 1 character over limit and it's not the longest name I've seen. Another example of long names could be snapshots. 

To avoid this problem I shortened the names like this:
VM Disks:  `{namingType}.vm.{vmId}.{diskId}`
VM Checkpoints:  `{namingType}.vm.{vmId}.cp`
Base images: `{namingType}.{imageId}`
VV Sets: `{namingType}.vm.{vmId}`

### CODE REVIEW

**Comment by kvaps** [comment]
Hi, thanks for your contribution. I'm not much into to accepting breaking changes without major reason for doing this. I believe that we can find any compromise.
As adding this change would require renaming all the existing devices on 3par and OpenNebula database, so we would need to describe the upgrading procedure, or provide option to continue using old naming.

Another question: can't we implement remote-copy without changing disk names?

**Comment by soudnyl** [comment]
I understand. But the advice to shorten the names came from HPE. If there's another way, it probably isn't too practical.

I do have a version of the driver aimed at transitioning the naming schemes and a script to rename the objects in 3PAR. Though it's made just to get the job done and then switch back to the regular driver with shortened names. If you want to give it a look-over, I can push it to a new branch in my repo.

**Comment by kvaps** [comment]
I think we can add information about required steps into release message. Since it is breaking change, we must bump major driver version.

Could you commit your script into this PR under `scripts/` directory, and describe upgrade steps from v2.0.0 to v3.0.0 in `UPGRADE.md` file?

Take a look at similar doc at [this project](https://github.com/piraeusdatastore/piraeus-operator/blob/master/UPGRADE.md) just for example.

**Comment by soudnyl** [comment]
Sure, I can do that. But it's not just a script, it includes a whole another version of the driver.

The whole upgrade procedure is to replace the 3PAR driver in ON cluster with a transition version, which supports both naming schemes. 
Then you run one script to rename objects in 3PAR, after that there's another script to rename all references to 3PAR VVs in ON database (using `onedb`).
Supposing nothing went wrong, you replace the 3PAR driver again with the version in this pull request.

While it has no downtime, it's tailor-made for our ON cluster and I can't guarantee it'll work for all the people running ON with 3PAR.

**Comment by soudnyl** [comment]
If I'm not mistaken, the changes in the transition version are contained in `datastore/3par/3par.py`, so that probably simplifies it.
I put it in the `interop` branch as my `UPGRADE.md` states.

Take a look, then we can figure out the rest.

**Pull request closed without merging**
